export const CONDITION_EFFECTS: string[] = [
  'Blinded',
  'Charmed',
  'Deafened',
  'Exhaustion',
  'Frightened',
  'Grappled',
  'Incapacitated',
  'Invisible',
  'Paralyzed',
  'Petrified',
  'Poisoned',
  'Prone',
  'Restrained',
  'Stunned',
  'Unconscious',
];

export const SPELL_STATUS_EFFECTS: string[] = [
  'Bless',
  'Bane',
  'Hex',
  "Hunter's Mark",
  'Faerie Fire',
  'Hold Person',
  'Confusion',
  'Haste',
  'Slow',
  'Concentration',
  'Sanctuary',
  'Shield of Faith',
  'Stoneskin',
  'Mirror Image',
  'Blur',
  'Fly',
  'Enlarge',
  'Reduce',
  'Web',
  'Entangle',
  'Silence',
  'Guidance',
  'Bardic Inspiration',
  'Polymorph',
  'Banishment',
  'Dominate Person',
  'Rage',
  'Dodge',
  'Dying',
  'Stable',
];

export const PRESET_EFFECTS: string[] = [...CONDITION_EFFECTS, ...SPELL_STATUS_EFFECTS];
