"""bugs.txt schema changes: creature favorites/player relation, spell images,
encounter random-tables

Revision ID: 60961abad1bf
Revises: ad59d3810c00
Create Date: 2026-08-15 00:00:00.000000

Hand-written (not autogenerated) per the baseline revision's own guidance -
001_schema.sql remains the source of truth for indexes/constraints and is
updated alongside this migration.

- creatures: is_favorite column; relation CHECK widened to allow 'player'.
- spells: image_asset_id column (mirrors items.image_asset_id).
- encounters: source_id/page/resolution_type/tables columns; campaign_id
  becomes nullable (imported random-table encounters are shared reference
  content, not campaign-owned - same pattern as creatures/spells/items);
  partial unique index on (name, source_id) for idempotent importer upserts.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60961abad1bf'
down_revision: Union[str, Sequence[str], None] = 'ad59d3810c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- creatures ----
    op.add_column(
        "creatures",
        sa.Column("is_favorite", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_constraint("creatures_relation_check", "creatures", type_="check")
    op.create_check_constraint(
        "creatures_relation_check",
        "creatures",
        "relation IS NULL OR relation IN ('ally','enemy','neutral','player')",
    )

    # ---- spells ----
    op.add_column(
        "spells",
        sa.Column("image_asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id"), nullable=True),
    )

    # ---- encounters ----
    op.add_column("encounters", sa.Column("source_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sources.id"), nullable=True))
    op.add_column("encounters", sa.Column("page", sa.Integer(), nullable=True))
    op.add_column(
        "encounters",
        sa.Column("resolution_type", sa.Text(), nullable=False, server_default="fixed"),
    )
    op.add_column("encounters", sa.Column("tables", postgresql.JSONB(), nullable=True))
    op.create_check_constraint(
        "encounters_resolution_type_check",
        "encounters",
        "resolution_type IN ('fixed','random_table')",
    )
    op.alter_column("encounters", "campaign_id", nullable=True)
    op.create_index("encounters_source_id_idx", "encounters", ["source_id"])
    op.create_index(
        "encounters_name_source_uidx",
        "encounters",
        ["name", "source_id"],
        unique=True,
        postgresql_where=sa.text("source_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("encounters_name_source_uidx", table_name="encounters")
    op.drop_index("encounters_source_id_idx", table_name="encounters")
    op.alter_column("encounters", "campaign_id", nullable=False)
    op.drop_constraint("encounters_resolution_type_check", "encounters", type_="check")
    op.drop_column("encounters", "tables")
    op.drop_column("encounters", "resolution_type")
    op.drop_column("encounters", "page")
    op.drop_column("encounters", "source_id")

    op.drop_column("spells", "image_asset_id")

    op.drop_constraint("creatures_relation_check", "creatures", type_="check")
    op.create_check_constraint(
        "creatures_relation_check",
        "creatures",
        "relation IS NULL OR relation IN ('ally','enemy','neutral')",
    )
    op.drop_column("creatures", "is_favorite")
