"""baseline: schema already applied via Database/Maintainance/sql/001_schema.sql

Revision ID: ad59d3810c00
Revises:
Create Date: 2026-08-14 19:43:29.219818

Intentionally a no-op. All 23 tables, indexes, triggers, and constraints
already exist in WorldWatcher_DB (applied by the Python importer's
Database/Maintainance/sql/001_schema.sql, which remains the source of
truth for indexes/constraints not mirrored in the ORM models). This
revision just gives Alembic a starting point via `alembic stamp head`
so every migration from here on is tracked normally.

Note: because several indexes/unique constraints from 001_schema.sql
aren't declared on the SQLAlchemy models (kept lean on purpose), a
future `alembic revision --autogenerate` will list them as "removed".
Always hand-review autogenerated migrations before applying - never
run one straight from `--autogenerate` without reading it first.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad59d3810c00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
