"""Import every model so they register on Base.metadata for Alembic autogenerate."""
from app.models.article import Article, ArticleFolder
from app.models.bastions import Bastion, BastionFacility, BastionFacilityInstance
from app.models.campaign import (
    Campaign,
    Character,
    Faction,
    FactionRelation,
    Location,
    Quest,
)
from app.models.combat import Combat, Combatant
from app.models.creatures import Creature, CreatureAction
from app.models.encounters import (
    Encounter,
    EncounterCombatBlock,
    EncounterCreature,
    EncounterExplorationBlock,
    EncounterNpc,
    EncounterReward,
    EncounterSocialBlock,
    EncounterTable,
    EncounterTableCreature,
)
from app.models.items import Item
from app.models.maps import Map, MapFloor, MapShape, MapToken, TokenLibrary
from app.models.note import Note, NoteFolder
from app.models.raw_entity import RawEntity
from app.models.reference import (
    Asset,
    Condition,
    Effect,
    RandomAppearance,
    RandomDungeonQuirk,
    RandomDungeonStateOfRuin,
    RandomMotivation,
    RandomName,
    RandomPersonality,
    RandomPitfall,
    RandomProfession,
    RandomRelationship,
    RandomSecret,
    RandomSettlementCalamity,
    RandomSettlementClaimToFame,
    RandomSettlementDefiningTrait,
    RandomSettlementEconomicSource,
    RandomSettlementLocalLeader,
    RandomSettlementRumorHook,
    RandomShopType,
    RandomTavernNamePart,
    Source,
)
from app.models.random_tables import (
    Category,
    EncounterTag,
    Generator,
    GeneratorComponent,
    GeneratorTag,
    RandomTable,
    RandomTableTag,
    Tag,
    TableColumn,
    TableEntry,
    TableEntryTag,
    TableFormat,
)
from app.models.item_usage import ItemUsage
from app.models.session_chat import SessionChat
from app.models.spells import Spell
from app.models.world import World

__all__ = [
    "World",
    "Article",
    "ArticleFolder",
    "Source",
    "Asset",
    "Condition",
    "Effect",
    "RandomName",
    "RandomProfession",
    "RandomMotivation",
    "RandomPitfall",
    "RandomAppearance",
    "RandomSecret",
    "RandomPersonality",
    "RandomRelationship",
    "RandomDungeonStateOfRuin",
    "RandomDungeonQuirk",
    "RandomShopType",
    "RandomTavernNamePart",
    "RandomSettlementDefiningTrait",
    "RandomSettlementClaimToFame",
    "RandomSettlementCalamity",
    "RandomSettlementLocalLeader",
    "RandomSettlementEconomicSource",
    "RandomSettlementRumorHook",
    "Creature",
    "CreatureAction",
    "Spell",
    "Item",
    "Campaign",
    "Character",
    "Location",
    "Faction",
    "FactionRelation",
    "Quest",
    "Map",
    "MapFloor",
    "TokenLibrary",
    "MapToken",
    "MapShape",
    "Encounter",
    "EncounterCreature",
    "EncounterTable",
    "EncounterTableCreature",
    "EncounterCombatBlock",
    "EncounterSocialBlock",
    "EncounterExplorationBlock",
    "EncounterNpc",
    "EncounterReward",
    "Combat",
    "Combatant",
    "RawEntity",
    "BastionFacility",
    "Bastion",
    "BastionFacilityInstance",
    "Note",
    "NoteFolder",
    "ItemUsage",
    "SessionChat",
    "Category",
    "Tag",
    "RandomTableTag",
    "EncounterTag",
    "GeneratorTag",
    "TableFormat",
    "RandomTable",
    "TableColumn",
    "TableEntry",
    "TableEntryTag",
    "Generator",
    "GeneratorComponent",
]
